# docker-compose.yml
version: "3.9"

services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - app-network

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
